export const clubMembersData = [
  {
    student_id: 1,
    club_id: 1,
    extra_groups: ['Group 1', 'Group 2'],
    comments: 'Comments 1',
    updated_by: 'Saket',
  },
  {
    student_id: 2,
    club_id: 2,
    extra_groups: ['Group 3', 'Group 4'],
    comments: 'Comments 2',
    updated_by: 'Sahitya',
  },
  {
    student_id: 3,
    club_id: 3,
    extra_groups: ['Group 5', 'Group 6'],
    comments: 'Comments 3',
    updated_by: 'Anurag',
  },
  {
    student_id: 4,
    club_id: 4,
    extra_groups: ['Group 7', 'Group 8'],
    comments: 'Comments 4',
    updated_by: 'Aditya',
  },
  {
    student_id: 5,
    club_id: 5,
    extra_groups: ['Group 9', 'Group 10'],
    comments: 'Comments 5',
    updated_by: 'Emma',
  },
  {
    student_id: 6,
    club_id: 6,
    extra_groups: ['Group 11', 'Group 12'],
    comments: 'Comments 6',
    updated_by: 'William',
  },
  {
    student_id: 7,
    club_id: 7,
    extra_groups: ['Group 13', 'Group 14'],
    comments: 'Comments 7',
    updated_by: 'Olivia',
  },
  {
    student_id: 8,
    club_id: 8,
    extra_groups: ['Group 15', 'Group 16'],
    comments: 'Comments 8',
    updated_by: 'James',
  },
  {
    student_id: 9,
    club_id: 9,
    extra_groups: ['Group 17', 'Group 18'],
    comments: 'Comments 9',
    updated_by: 'Sophia',
  },
  {
    student_id: 10,
    club_id: 10,
    extra_groups: ['Group 19', 'Group 20'],
    comments: 'Comments 10',
    updated_by: 'Ethan',
  },
];
