export const coursesData = [
  {
    code: '1',
    title: 'Introduction to Business Administration',
    prerequisites: [],
    kind: 'Theory',
    lecture_credits: 3,
    tutorial_credits: 1,
    practical_credits: 0,
    major_id: 1,
    semester: 1,
    objectives: [
      'To introduce the students to the field of business administration',
    ],
    content: 'The course will cover the basics of business administration',
    outcomes: [
      'The students will be able to understand the basics of business administration',
    ],
    books: ['Business Administration by John Doe'],
    similar: [],
  },
  {
    code: '2',
    title: 'Introduction to Chemistry',
    prerequisites: [],
    kind: 'Theory',
    lecture_credits: 3,
    tutorial_credits: 1,
    practical_credits: 0,
    major_id: 2,
    semester: 1,
    objectives: ['To introduce the students to the field of chemistry'],
    content: 'The course will cover the basics of chemistry',
    outcomes: [
      'The students will be able to understand the basics of chemistry',
    ],
    books: ['Chemistry by Jane Doe'],
    similar: [],
  },
  {
    code: '3',
    title: 'Introduction to Civil Engineering',
    prerequisites: [],
    kind: 'Theory',
    lecture_credits: 3,
    tutorial_credits: 1,
    practical_credits: 0,
    major_id: 3,
    semester: 1,
    objectives: ['To introduce the students to the field of civil engineering'],
    content: 'The course will cover the basics of civil engineering',
    outcomes: [
      'The students will be able to understand the basics of civil engineering',
    ],
    books: ['Civil Engineering by John Doe'],
    similar: [],
  },
  {
    code: '4',
    title: 'Introduction to Computer Engineering',
    prerequisites: [],
    kind: 'Theory',
    lecture_credits: 3,
    tutorial_credits: 1,
    practical_credits: 0,
    major_id: 4,
    semester: 1,
    objectives: [
      'To introduce the students to the field of computer engineering',
    ],
    content: 'The course will cover the basics of computer engineering',
    outcomes: [
      'The students will be able to understand the basics of computer engineering',
    ],
    books: ['Computer Engineering by Jane Doe'],
    similar: [],
  },
  {
    code: '5',
    title: 'Introduction to Electrical Engineering',
    prerequisites: [],
    kind: 'Theory',
    lecture_credits: 3,
    tutorial_credits: 1,
    practical_credits: 0,
    major_id: 5,
    semester: 1,
    objectives: [
      'To introduce the students to the field of electrical engineering',
    ],
    content: 'The course will cover the basics of electrical engineering',
    outcomes: [
      'The students will be able to understand the basics of electrical engineering',
    ],
    books: ['Electrical Engineering by John Doe'],
    similar: [],
  },
  {
    code: '6',
    title: 'Introduction to Electronics & Communication Engineering',
    prerequisites: [],
    kind: 'Theory',
    lecture_credits: 3,
    tutorial_credits: 1,
    practical_credits: 0,
    major_id: 6,
    semester: 1,
    objectives: [
      'To introduce the students to the field of electronics & communication engineering',
    ],
    content:
      'The course will cover the basics of electronics & communication engineering',
    outcomes: [
      'The students will be able to understand the basics of electronics & communication engineering',
    ],
    books: ['Electronics & Communication Engineering by Jane Doe'],
    similar: [],
  },
  {
    code: '7',
    title: 'Introduction to Humanities & Social Sciences',
    prerequisites: [],
    kind: 'Theory',
    lecture_credits: 3,
    tutorial_credits: 1,
    practical_credits: 0,
    major_id: 7,
    semester: 1,
    objectives: [
      'To introduce the students to the field of humanities & social sciences',
    ],
    content: 'The course will cover the basics of humanities & social sciences',
    outcomes: [
      'The students will be able to understand the basics of humanities & social sciences',
    ],
    books: ['Humanities & Social Sciences by John Doe'],
    similar: [],
  },
  {
    code: '8',
    title: 'Introduction to Mathematics',
    prerequisites: [],
    kind: 'Theory',
    lecture_credits: 3,
    tutorial_credits: 1,
    practical_credits: 0,
    major_id: 8,
    semester: 1,
    objectives: ['To introduce the students to the field of mathematics'],
    content: 'The course will cover the basics of mathematics',
    outcomes: [
      'The students will be able to understand the basics of mathematics',
    ],
    books: ['Mathematics by Jane Doe'],
    similar: [],
  },
  {
    code: '9',
    title: 'Introduction to Mechanical Engineering',
    prerequisites: [],
    kind: 'Theory',
    lecture_credits: 3,
    tutorial_credits: 1,
    practical_credits: 0,
    major_id: 9,
    semester: 1,
    objectives: [
      'To introduce the students to the field of mechanical engineering',
    ],
    content: 'The course will cover the basics of mechanical engineering',
    outcomes: [
      'The students will be able to understand the basics of mechanical engineering',
    ],
    books: ['Mechanical Engineering by John Doe'],
    similar: [],
  },
  {
    code: '10',
    title: 'Introduction to Physics',
    prerequisites: [],
    kind: 'Theory',
    lecture_credits: 3,
    tutorial_credits: 1,
    practical_credits: 0,
    major_id: 10,
    semester: 1,
    objectives: ['To introduce the students to the field of physics'],
    content: 'The course will cover the basics of physics',
    outcomes: ['The students will be able to understand the basics of physics'],
    books: ['Physics by Jane Doe'],
    similar: [],
  },
];
