export const courseLogsData = [
  {
    session: '2023-01-10',
    course_id: 1,
    faculty_id: 1,
    major_id: 1,
    semester: 1,
    section: 'A',
    sub_section: 1,
  },
  {
    session: '2023-02-10',
    course_id: 2,
    faculty_id: 2,
    major_id: 2,
    semester: 1,
    section: 'B',
    sub_section: 2,
  },
  {
    session: '2023-03-10',
    course_id: 3,
    faculty_id: 3,
    major_id: 3,
    semester: 1,
    section: 'C',
    sub_section: 3,
  },
  {
    session: '2023-04-10',
    course_id: 4,
    faculty_id: 4,
    major_id: 4,
    semester: 1,
    section: 'D',
    sub_section: 4,
  },
  {
    session: '2023-05-10',
    course_id: 5,
    faculty_id: 5,
    major_id: 5,
    semester: 1,
    section: 'E',
    sub_section: 5,
  },
  {
    session: '2023-06-10',
    course_id: 6,
    faculty_id: 6,
    major_id: 6,
    semester: 1,
    section: 'F',
    sub_section: 6,
  },
  {
    session: '2023-07-10',
    course_id: 7,
    faculty_id: 7,
    major_id: 7,
    semester: 1,
    section: 'G',
    sub_section: 7,
  },
  {
    session: '2023-08-10',
    course_id: 8,
    faculty_id: 8,
    major_id: 8,
    semester: 1,
    section: 'H',
    sub_section: 8,
  },
  {
    session: '2023-09-10',
    course_id: 9,
    faculty_id: 9,
    major_id: 9,
    semester: 1,
    section: 'I',
    sub_section: 9,
  },
  {
    session: '2023-10-10',
    course_id: 10,
    faculty_id: 10,
    major_id: 10,
    semester: 1,
    section: 'J',
    sub_section: 10,
  },
];
