export const deansData = [
  {
    domain: 'Academics',
    faculty_id: 1,
    activity_logs: ['Activity 1'],
    associate_faculty_id: 2,
    staff_id: ['1'],
  },
  {
    domain: 'Research',
    faculty_id: 2,
    activity_logs: ['Activity 2'],
    associate_faculty_id: 3,
    staff_id: ['2'],
  },
  {
    domain: 'Students',
    faculty_id: 3,
    activity_logs: ['Activity 3'],
    associate_faculty_id: 4,
    staff_id: ['3'],
  },
  {
    domain: 'Faculty',
    faculty_id: 4,
    activity_logs: [],
    associate_faculty_id: 5,
    staff_id: ['4'],
  },
  {
    domain: 'Alumni',
    faculty_id: 5,
    activity_logs: [],
    associate_faculty_id: 6,
    staff_id: ['5'],
  },
  {
    domain: 'International Relations',
    faculty_id: 6,
    activity_logs: [],
    associate_faculty_id: 7,
    staff_id: ['6'],
  },
  {
    domain: 'Industry Relations',
    faculty_id: 7,
    activity_logs: [],
    associate_faculty_id: 8,
    staff_id: ['7'],
  },
  {
    domain: 'Administration',
    faculty_id: 8,
    activity_logs: [],
    associate_faculty_id: 9,
    staff_id: ['8'],
  },
  {
    domain: 'Finance',
    faculty_id: 9,
    activity_logs: [],
    associate_faculty_id: 10,
    staff_id: ['9'],
  },
  {
    domain: 'Infrastructure',
    faculty_id: 10,
    activity_logs: [],
    associate_faculty_id: 1,
    staff_id: ['10'],
  },
];
