export const facultyData = [
  {
    name: 'Dr. Vikram Singh',
    department_id: 4,
    image: '',
    designation: 'Assistant Professor',
    email: 'viks@nitkkr.ac.in',
    office_telephone: '01744233530',
    is_active: true,
    joined_on: new Date('2013-02-13'),
    home_telephone: '0987654321',
    teaching_interests: ['Computer Networks', 'Data Structures'],
    research_interests: ['Machine Learning', 'Big Data Analytics'],
    patents: ['US Patent 1234567', 'EU Patent 7654321'],
    copyrights: ['Copyright 9876543', 'Copyright 5432167'],
    journals: [
      'Journal of Computer Science',
      'IEEE Transactions on Networking',
    ],
    conferences: [
      'International Conference on Information Technology',
      'ACM SIGCOMM',
    ],
    books: ['Data Structures and Algorithms', 'Network Security'],
    areas_of_interest: ['Computer Networks', 'Data Structures'],
    workshops: ['Machine Learning Workshop', 'Big Data Analytics Workshop'],
    research_projects: [
      'Enhancing Network Security Using Machine Learning',
      'Optimizing Big Data Analytics for Real-time Applications',
    ],
    expert_lectures: ['10 delivered', '5 invited'],
    awards: ['Best Paper Award', 'Outstanding Researcher Award'],
    admin_roles: ['Dean', 'HOD'],
    outreach: ['Community Service', 'Industry Collaboration'],
    e_content: ['www.example.com/econtent'],
    research_supervision: { ongoing: 5, completed: 3 },
    google_scholar_profile: 'www.google.com/profile/vikramsingh',
    orchid_profile: 'www.orchid.com/profile/vikramsingh',
    scopus_profile: 'www.scopus.com/profile/vikramsingh',
    role_ids: [1],
  },
  {
    name: 'Dr. J.K. Chhabra',
    department_id: 4,
    image: '',
    designation: 'Professor',
    email: 'jitenderchhabra@nitkkr.ac.in',
    office_telephone: '1744-233482',
    joined_on: new Date('2020-01-15'),
    is_active: true,
    home_telephone: '9416733789',
    teaching_interests: ['Computer Networks', 'Data Structures'],
    research_interests: ['Machine Learning', 'Big Data Analytics'],
    patents: ['US Patent 1234567', 'EU Patent 7654321'],
    copyrights: ['Copyright 9876543', 'Copyright 5432167'],
    journals: [
      'Journal of Computer Science',
      'IEEE Transactions on Networking',
    ],
    conferences: [
      'International Conference on Information Technology',
      'ACM SIGCOMM',
    ],
    books: ['Data Structures and Algorithms', 'Network Security'],
    areas_of_interest: ['Computer Networks', 'Data Structures'],
    workshops: ['Machine Learning Workshop', 'Big Data Analytics Workshop'],
    research_supervision: { ongoing: 5, completed: 3 },
    expert_lectures: ['10 delivered', '5 invited'],
    awards: ['Best Paper Award', 'Outstanding Researcher Award'],
    admin_roles: ['Dean', 'HOD'],
    outreach: ['Community Service', 'Industry Collaboration'],
    e_content: ['www.example.com/econtent'],
    research_projects: [
      'Enhancing Network Security Using Machine Learning',
      'Optimizing Big Data Analytics for Real-time Applications',
    ],
    google_scholar_profile: 'www.google.com/profile/johnsmith',
    orchid_profile: 'www.orchid.com/profile/johnsmith',
    scopus_profile: 'www.scopus.com/profile/johnsmith',
    role_ids: [1],
  },
  {
    name: 'Dr. Awadhesh Kumar Singh',
    department_id: 4,
    image: '',
    designation: 'Professor',
    email: 'aksingh@nitkkr.ac.in',
    office_telephone: '233481',
    joined_on: new Date('2018-05-20'),
    is_active: true,
    home_telephone: '09416570992',
    teaching_interests: ['Artificial Intelligence', 'Database Systems'],
    research_interests: ['Natural Language Processing', 'Data Mining'],
    patents: ['US Patent 9876543', 'EU Patent 8765432'],
    copyrights: ['Copyright 2345678', 'Copyright 8765432'],
    journals: [
      'Journal of Artificial Intelligence Research',
      'ACM Transactions on Database Systems',
    ],
    conferences: [
      'International Conference on Artificial Intelligence',
      'IEEE International Conference on Data Mining',
    ],
    books: ['Computer Networks', 'Data Structures'],
    areas_of_interest: ['Advanced Database Systems', 'Machine Learning Basics'],
    workshops: ['NLP Workshop', 'Data Mining Workshop'],
    research_supervision: { ongoing: 3, completed: 8 },
    expert_lectures: ['8 delivered', '4 invited'],
    awards: ['Best Teacher Award', 'Young Researcher Award'],
    admin_roles: ['HOD', 'Research Coordinator'],
    outreach: ['Community Service', 'Academic Collaboration'],
    e_content: ['www.example.com/econtent'],
    research_projects: [
      'Enhancing Network Security Using Machine Learning',
      'Optimizing Big Data Analytics for Real-time Applications',
    ],
    google_scholar_profile: 'www.google.com/profile/janedoe',
    orchid_profile: 'www.orchid.com/profile/janedoe',
    scopus_profile: 'www.scopus.com/profile/janedoe',
    role_ids: [2],
  },
  {
    name: 'Arun Goel',
    department_id: 3,
    image: '',
    designation: 'Professor',
    email: 'drarun_goel@yahoo.co.in',
    office_telephone: '01744-233300',
    joined_on: new Date('2019-08-10'),
    is_active: true,
    home_telephone: '01744-233349',
    teaching_interests: ['Software Engineering', 'Distributed Systems'],
    research_interests: ['Cloud Computing', 'Internet of Things'],
    patents: ['US Patent 2345678', 'EU Patent 7654321'],
    copyrights: ['Copyright 3456789', 'Copyright 6543210'],
    journals: [
      'Journal of Software Engineering',
      'IEEE Transactions on Cloud Computing',
    ],
    conferences: [
      'International Conference on Software Engineering',
      'ACM/IEEE Conference on Internet of Things',
    ],
    books: ['Computer Networks', 'Data Structures'],
    areas_of_interest: [
      'Software Design Patterns',
      'Distributed Systems Architectures',
    ],
    workshops: ['Cloud Computing Workshop', 'IoT Workshop'],
    research_supervision: { ongoing: 6, completed: 4 },
    expert_lectures: ['7 delivered', '3 invited'],
    awards: ['Best Research Paper Award', 'Outstanding Educator Award'],
    admin_roles: ['Research Coordinator', 'Publication Chair'],
    outreach: ['Industry Collaboration', 'Student Mentorship'],
    e_content: ['www.example.com/econtent'],
    research_projects: [
      'Enhancing Network Security Using Machine Learning',
      'Optimizing Big Data Analytics for Real-time Applications',
    ],
    google_scholar_profile: 'www.google.com/profile/michaeljohnson',
    orchid_profile: 'www.orchid.com/profile/michaeljohnson',
    scopus_profile: 'www.scopus.com/profile/michaeljohnson',
    role_ids: [3],
  },
  {
    name: 'Jitander Kumar Kapoor',
    department_id: 2,
    image: '',
    designation: 'Associate Professor',
    email: 'jkkapoor11@gmail.com',
    office_telephone: '1234567890',
    joined_on: new Date('2021-03-05'),
    is_active: true,
    home_telephone: '0987654321',
    teaching_interests: ['Software Testing', 'Human-Computer Interaction'],
    research_interests: [
      'Organic Synthesis and Pharmacetical /Medicinal interest',
      'Test Automation',
    ],
    patents: ['US Patent 3456789', 'EU Patent 6543210'],
    copyrights: ['Copyright 4567890', 'Copyright 5432109'],
    journals: [
      'Journal of Software Testing',
      'ACM Transactions on Human-Computer Interaction',
    ],
    conferences: [
      'International Conference on Software Testing',
      'HCI International Conference',
    ],
    books: ['Computer Networks', 'Data Structures'],
    areas_of_interest: ['Software Quality Assurance', 'User Experience Design'],
    workshops: ['Testing Tools Workshop', 'HCI Prototyping Workshop'],
    research_supervision: { ongoing: 4, completed: 6 },
    expert_lectures: ['5 delivered', '6 invited'],
    awards: ['Best Paper Award', 'Excellence in Teaching Award'],
    admin_roles: ['HOD', 'Dean'],
    outreach: ['Community Service', 'Academic Collaboration'],
    e_content: ['www.example.com/econtent'],
    research_projects: [
      'Enhancing Network Security Using Machine Learning',
      'Optimizing Big Data Analytics for Real-time Applications',
    ],
    google_scholar_profile: 'www.google.com/profile/emilywilson',
    orchid_profile: 'www.orchid.com/profile/emilywilson',
    scopus_profile: 'www.scopus.com/profile/emilywilson',
    role_ids: [4],
  },
  {
    name: 'Jyoti Ohri',
    department_id: 5,
    image: '',
    designation: 'Associate Professor',
    email: 'ohrijyoti@nitkkr.ac.in',
    office_telephone: '1234567890',
    joined_on: new Date('2020-12-12'),
    is_active: true,
    home_telephone: '0987654321',
    teaching_interests: ['Computer Graphics', 'Computer Vision'],
    research_interests: ['Image Processing', 'Virtual Reality'],
    patents: ['US Patent 4567890', 'EU Patent 5432109'],
    copyrights: ['Copyright 5678901', 'Copyright 4321098'],
    journals: [
      'Journal of Computer Graphics',
      'IEEE Transactions on Computer Vision',
    ],
    conferences: ['International Conference on Computer Graphics', 'CVPR'],
    books: ['Rendering Techniques', 'Object Detection'],
    areas_of_interest: ['Rendering Techniques', 'Object Detection'],
    workshops: ['Computer Graphics Workshop', 'Computer Vision Workshop'],
    research_supervision: { ongoing: 8, completed: 2 },
    expert_lectures: ['9 delivered', '2 invited'],
    awards: ['Best Research Paper Award', 'Teaching Excellence Award'],
    admin_roles: ['Research Coordinator', 'Head of Lab'],
    outreach: ['Industry Collaboration', 'Student Mentorship'],
    e_content: ['www.example.com/econtent'],
    research_projects: [
      'Enhancing Network Security Using Machine Learning',
      'Optimizing Big Data Analytics for Real-time Applications',
    ],
    google_scholar_profile: 'www.google.com/profile/danielbrown',
    orchid_profile: 'www.orchid.com/profile/danielbrown',
    scopus_profile: 'www.scopus.com/profile/danielbrown',
    role_ids: [5],
  },
  {
    name: 'Karan Sharma',
    department_id: 6,
    image: '',
    designation: 'Associate Professor',
    email: 'ksharma_nitk@yahoo.co.in',
    office_telephone: '1234567890',
    joined_on: new Date('2019-09-30'),
    is_active: true,
    home_telephone: '0987654321',
    teaching_interests: ['Algorithms', 'Computer Security'],
    research_interests: ['Cryptography', 'Blockchain Technology'],
    patents: ['US Patent 5678901', 'EU Patent 4321098'],
    copyrights: ['Copyright 6789012', 'Copyright 3210987'],
    journals: [
      'Journal of Algorithms',
      'IEEE Transactions on Information Security',
    ],
    conferences: ['International Conference on Algorithms', 'ACM CCS'],
    books: ['Rendering Techniques', 'Object Detection'],
    areas_of_interest: ['Algorithm Design', 'Network Security'],
    workshops: ['Cryptography Workshop', 'Blockchain Technology Workshop'],
    research_supervision: { ongoing: 7, completed: 3 },
    expert_lectures: ['6 delivered', '4 invited'],
    awards: ['Best Paper Award', 'Young Researcher Award'],
    admin_roles: ['Publication Chair', 'HOD'],
    outreach: ['Industry Collaboration', 'Research Funding'],
    e_content: ['www.example.com/econtent'],
    research_projects: [
      'Enhancing Network Security Using Machine Learning',
      'Optimizing Big Data Analytics for Real-time Applications',
    ],
    google_scholar_profile: 'www.google.com/profile/oliviataylor',
    orchid_profile: 'www.orchid.com/profile/oliviataylor',
    scopus_profile: 'www.scopus.com/profile/oliviataylor',
    role_ids: [6],
  },
  {
    name: 'Vikas Chaudhary',
    department_id: 7,
    image: '',
    designation: 'Professor',
    email: 'vc_hss@yahoo.com',
    office_telephone: '1234567890',
    joined_on: new Date('2022-06-20'),
    is_active: true,
    home_telephone: '0987654321',
    teaching_interests: ['Machine Learning', 'Pattern Recognition'],
    research_interests: ['Deep Learning', 'Computer Vision'],
    patents: ['US Patent 6789012', 'EU Patent 3210987'],
    copyrights: ['Copyright 7890123', 'Copyright 2109876'],
    journals: [
      'Journal of Machine Learning Research',
      'IEEE Transactions on Pattern Analysis and Machine Intelligence',
    ],
    conferences: ['International Conference on Machine Learning', 'CVPR'],
    books: ['Rendering Techniques', 'Object Detection'],
    areas_of_interest: ['Machine Learning Algorithms', 'Image Recognition'],
    workshops: ['Deep Learning Workshop', 'Pattern Recognition Workshop'],
    research_supervision: { ongoing: 9, completed: 1 },
    expert_lectures: ['8 delivered', '2 invited'],
    awards: ['Best Research Paper Award', 'Outstanding Educator Award'],
    admin_roles: ['Dean', 'HOD'],
    outreach: ['Academic Collaboration', 'Student Mentorship'],
    e_content: ['www.example.com/econtent'],
    research_projects: [
      'Enhancing Network Security Using Machine Learning',
      'Optimizing Big Data Analytics for Real-time Applications',
    ],
    google_scholar_profile: 'www.google.com/profile/sophiamartinez',
    orchid_profile: 'www.orchid.com/profile/sophiamartinez',
    scopus_profile: 'www.scopus.com/profile/sophiamartinez',
    role_ids: [7],
  },
  {
    name: 'A. S. V Ravi Kanth',
    department_id: 8,
    image: '',
    designation: 'Associate Professor',
    email: 'asvravikanth@yahoo.com',
    office_telephone: '1234567890',
    joined_on: new Date('2018-12-05'),
    is_active: true,
    home_telephone: '0987654321',
    teaching_interests: ['Computer Architecture', 'Operating Systems'],
    research_interests: ['Parallel Computing', 'Embedded Systems'],
    patents: ['US Patent 7890123', 'EU Patent 2109876'],
    copyrights: ['Copyright 8901234', 'Copyright 1098765'],
    journals: [
      'Journal of Computer Architecture',
      'IEEE Transactions on Operating Systems',
    ],
    conferences: ['International Conference on Computer Architecture', 'OSDI'],
    books: ['Rendering Techniques', 'Object Detection'],
    areas_of_interest: ['Processor Design', 'Memory Management'],
    workshops: ['Parallel Computing Workshop', 'Embedded Systems Workshop'],
    research_supervision: { ongoing: 10, completed: 0 },
    expert_lectures: ['10 delivered', '0 invited'],
    awards: ['Best Paper Award', 'Excellence in Teaching Award'],
    admin_roles: ['Head of Lab', 'Research Coordinator'],
    outreach: ['Academic Collaboration', 'Student Mentorship'],
    e_content: ['www.example.com/econtent'],
    research_projects: [
      'Enhancing Network Security Using Machine Learning',
      'Optimizing Big Data Analytics for Real-time Applications',
    ],
    google_scholar_profile: 'www.google.com/profile/liamanderson',
    orchid_profile: 'www.orchid.com/profile/liamanderson',
    scopus_profile: 'www.scopus.com/profile/liamanderson',
    role_ids: [8],
  },
  {
    name: 'Hari Singh',
    department_id: 9,
    image: '',
    designation: 'Professor',
    email: 'hsinghfme@nitkkr.ac.in',
    office_telephone: '1234567890',
    joined_on: new Date('2021-11-17'),
    is_active: true,
    home_telephone: '0987654321',
    teaching_interests: ['Mobile Computing', 'Wireless Networks'],
    research_interests: [
      'Internet of Things',
      'Mobile Application Development',
    ],
    patents: ['US Patent 8901234', 'EU Patent 1098765'],
    copyrights: ['Copyright 9012345', 'Copyright 0987654'],
    journals: [
      'Journal of Mobile Computing',
      'IEEE Transactions on Wireless Communications',
    ],
    conferences: ['International Conference on Mobile Computing', 'INFOCOM'],
    books: ['Rendering Techniques', 'Object Detection'],
    areas_of_interest: ['Mobile Application Design', 'Wireless Protocols'],
    workshops: ['IoT Workshop', 'Mobile App Development Workshop'],
    research_supervision: { ongoing: 2, completed: 8 },
    expert_lectures: ['4 delivered', '6 invited'],
    awards: ['Best Research Paper Award', 'Young Researcher Award'],
    admin_roles: ['Publication Chair', 'Research Coordinator'],
    outreach: ['Academic Collaboration', 'Research Funding'],
    e_content: ['www.example.com/econtent'],
    research_projects: [
      'Enhancing Network Security Using Machine Learning',
      'Optimizing Big Data Analytics for Real-time Applications',
    ],
    google_scholar_profile: 'www.google.com/profile/miawilson',
    orchid_profile: 'www.orchid.com/profile/miawilson',
    scopus_profile: 'www.scopus.com/profile/miawilson',
    role_ids: [9],
  },
  {
    name: 'Neena Jaggi',
    department_id: 10,
    image: '',
    designation: 'Professor',
    email: 'jaggineena@nitkkr.ac.in',
    office_telephone: '1234567890',
    joined_on: new Date('2023-03-10'),
    is_active: true,
    home_telephone: '0987654321',
    teaching_interests: ['Computer Networks', 'Data Structures'],
    research_interests: ['Machine Learning', 'Big Data Analytics'],
    patents: ['US Patent 1234567', 'EU Patent 7654321'],
    copyrights: ['Copyright 9876543', 'Copyright 5432167'],
    journals: [
      'Journal of Computer Science',
      'IEEE Transactions on Networking',
    ],
    conferences: [
      'International Conference on Information Technology',
      'ACM SIGCOMM',
    ],
    books: ['Data Structures and Algorithms', 'Network Security'],
    areas_of_interest: ['Computer Networks', 'Data Structures'],
    workshops: ['Machine Learning Workshop', 'Big Data Analytics Workshop'],
    research_supervision: { ongoing: 5, completed: 3 },
    expert_lectures: ['10 delivered', '5 invited'],
    awards: ['Best Paper Award', 'Outstanding Researcher Award'],
    admin_roles: ['Dean', 'HOD'],
    outreach: ['Community Service', 'Industry Collaboration'],
    e_content: ['www.example.com/econtent'],
    research_projects: [
      'Enhancing Network Security Using Machine Learning',
      'Optimizing Big Data Analytics for Real-time Applications',
    ],
    google_scholar_profile: 'www.google.com/profile/johnsmith',
    orchid_profile: 'www.orchid.com/profile/johnsmith',
    scopus_profile: 'www.scopus.com/profile/johnsmith',
    role_ids: [1],
  },
];
