export const formQuestionsData = [
  {
    form_id: 1,
    question: 'Name',
    description: 'Enter your name',
    is_required: true,
    input_type: 'text',
    page_number: 1,
  },
  {
    form_id: 1,
    question: 'Email',
    description: 'Enter your email',
    is_required: true,
    input_type: 'email',
    page_number: 1,
  },
  {
    form_id: 1,
    question: 'Telephone',
    description: 'Enter your telephone number',
    is_required: true,
    input_type: 'number',
    page_number: 1,
  },
  {
    form_id: 1,
    question: 'Address',
    description: 'Enter your address',
    is_required: true,
    input_type: 'text',
    page_number: 1,
  },
  {
    form_id: 1,
    question: 'Date of Birth',
    description: 'Enter your date of birth',
    is_required: true,
    input_type: 'date',
    page_number: 1,
  },
  {
    form_id: 2,
    question: 'Course Code',
    description: 'Enter the course code',
    is_required: true,
    input_type: 'text',
    page_number: 1,
  },
  {
    form_id: 2,
    question: 'Faculty Name',
    description: 'Enter the faculty name',
    is_required: true,
    input_type: 'text',
    page_number: 1,
  },
  {
    form_id: 2,
    question: 'Feedback',
    description: 'Enter your feedback',
    is_required: true,
    input_type: 'text',
    page_number: 1,
  },
  {
    form_id: 2,
    question: 'Rating',
    description: 'Enter your rating',
    is_required: true,
    input_type: 'number',
    page_number: 1,
  },
  {
    form_id: 2,
    question: 'Date',
    description: 'Enter the date',
    is_required: true,
    input_type: 'date',
    page_number: 1,
  },
  {
    form_id: 3,
    question: 'Name',
    description: 'Enter your name',
    is_required: true,
    input_type: 'text',
    page_number: 1,
  },
  {
    form_id: 3,
    question: 'Email',
    description: 'Enter your email',
    is_required: true,
    input_type: 'email',
    page_number: 1,
  },
  {
    form_id: 3,
    question: 'Telephone',
    description: 'Enter your telephone number',
    is_required: true,
    input_type: 'number',
    page_number: 1,
  },
  {
    form_id: 3,
    question: 'Address',
    description: 'Enter your address',
    is_required: true,
    input_type: 'text',
    page_number: 1,
  },
  {
    form_id: 3,
    question: 'Date of Birth',
    description: 'Enter your date of birth',
    is_required: true,
    input_type: 'date',
    page_number: 1,
  },
  {
    form_id: 4,
    question: 'Name',
    description: 'Enter your name',
    is_required: true,
    input_type: 'text',
    page_number: 1,
  },
  {
    form_id: 4,
    question: 'Email',
    description: 'Enter your email',
    is_required: true,
    input_type: 'email',
    page_number: 1,
  },
  {
    form_id: 4,
    question: 'Telephone',
    description: 'Enter your telephone number',
    is_required: true,
    input_type: 'number',
    page_number: 1,
  },
  {
    form_id: 4,
    question: 'Address',
    description: 'Enter your address',
    is_required: true,
    input_type: 'text',
    page_number: 1,
  },
  {
    form_id: 4,
    question: 'Date of Birth',
    description: 'Enter your date of birth',
    is_required: true,
    input_type: 'date',
    page_number: 1,
  },
  {
    form_id: 5,
    question: 'Name',
    description: 'Enter your name',
    is_required: true,
    input_type: 'text',
    page_number: 1,
  },
  {
    form_id: 5,
    question: 'Email',
    description: 'Enter your email',
    is_required: true,
    input_type: 'email',
    page_number: 1,
  },
  {
    form_id: 5,
    question: 'Telephone',
    description: 'Enter your telephone number',
    is_required: true,
    input_type: 'number',
    page_number: 1,
  },
  {
    form_id: 5,
    question: 'Address',
    description: 'Enter your address',
    is_required: true,
    input_type: 'text',
    page_number: 1,
  },
  {
    form_id: 5,
    question: 'Date of Birth',
    description: 'Enter your date of birth',
    is_required: true,
    input_type: 'date',
    page_number: 1,
  },
  {
    form_id: 6,
    question: 'Name',
    description: 'Enter your name',
    is_required: true,
    input_type: 'text',
    page_number: 1,
  },
  {
    form_id: 6,
    question: 'Email',
    description: 'Enter your email',
    is_required: true,
    input_type: 'email',
    page_number: 1,
  },
  {
    form_id: 6,
    question: 'Telephone',
    description: 'Enter your telephone number',
    is_required: true,
    input_type: 'number',
    page_number: 1,
  },
  {
    form_id: 6,
    question: 'Address',
    description: 'Enter your address',
    is_required: true,
    input_type: 'text',
    page_number: 1,
  },
  {
    form_id: 6,
    question: 'Date of Birth',
    description: 'Enter your date of birth',
    is_required: true,
    input_type: 'date',
    page_number: 1,
  },
];
