export const formsData = [
  {
    title: 'Registration Form',
    description: 'This form is used to register students for the college',
    visible_to: ['Students'],
    questions: [1, 2, 3, 4],
    is_editing_allowed: true,
    expiry_date: new Date('2024-03-10'),
    persistent_url: 'form-url.com',
    old_persistent_urls: [],
    is_published: false,
  },
  {
    title: 'Feedback Form',
    description: 'This form is used to collect feedback from students',
    visible_to: ['Students', 'HODs'],
    questions: [1, 2, 3],
    is_editing_allowed: true,
    expiry_date: new Date('2024-03-10'),
    persistent_url: 'form-url.com',
    old_persistent_urls: [],
    is_published: false,
  },
  {
    title: 'Complaint Form',
    description: 'This form is used to collect complaints from students',
    visible_to: ['Students', 'Director'],
    questions: [1, 2],
    is_editing_allowed: true,
    expiry_date: new Date('2024-03-15'),
    persistent_url: 'form-url.com',
    old_persistent_urls: [],
    is_published: false,
  },
  {
    title: 'Application Form',
    description: 'This form is used to collect applications from students',
    visible_to: ['Students'],
    questions: [1, 2, 3, 4],
    is_editing_allowed: true,
    expiry_date: new Date('2024-03-15'),
    persistent_url: 'form-url.com',
    old_persistent_urls: [],
    is_published: false,
  },
  {
    title: 'Club Registration Form',
    description: 'This form is used to register students for the clubs',
    visible_to: ['Students', 'Club Presidents'],
    questions: [1, 2],
    is_editing_allowed: true,
    expiry_date: new Date('2024-03-15'),
    persistent_url: 'form-url.com',
    old_persistent_urls: [],
    is_published: false,
  },
  {
    title: 'Event Registration Form',
    description: 'This form is used to register students for the events',
    visible_to: ['Students'],
    questions: [1, 2, 3, 4],
    is_editing_allowed: true,
    expiry_date: new Date('2024-03-15'),
    persistent_url: 'form-url.com',
    old_persistent_urls: ['old-form-url.com'],
    is_published: false,
  },
  {
    title: 'Hostel Registration Form',
    description: 'This form is used to register students for the hostel',
    visible_to: ['Students'],
    questions: [1, 2, 3, 4],
    is_editing_allowed: true,
    expiry_date: new Date('2024-03-15'),
    persistent_url: 'form-url.com',
    old_persistent_urls: [],
    is_published: false,
  },
  {
    title: 'Library Registration Form',
    description: 'This form is used to register students for the library',
    visible_to: ['Students', 'Faculty'],
    questions: [1, 2, 3, 4],
    is_editing_allowed: true,
    expiry_date: new Date('2024-03-15'),
    persistent_url: 'form-url.com',
    old_persistent_urls: [],
    is_published: false,
  },
  {
    title: 'Placement Registration Form',
    description: 'This form is used to register students for the placement',
    visible_to: ['Students', 'Training and Placement Officer'],
    questions: [1, 2, 3, 4],
    is_editing_allowed: true,
    expiry_date: new Date('2024-03-15'),
    persistent_url: 'form-url.com',
    old_persistent_urls: [],
    is_published: false,
  },
  {
    title: 'Alumni Registration Form',
    description: 'This form is used to register students for the alumni',
    visible_to: ['Students', 'Director'],
    questions: [1, 2, 3, 4],
    is_editing_allowed: true,
    expiry_date: new Date('2024-03-15'),
    persistent_url: 'form-url.com',
    old_persistent_urls: [],
    is_published: false,
  },
];
