export const majorsData = [
  {
    name: 'MBA',
    alias: 'M',
    department_id: 1,
    degree: 'Post Graduation',
  },
  {
    name: 'MCA',
    alias: 'M',
    department_id: 4,
    degree: 'Post Graduation',
  },
  {
    name: 'B.Tech',
    alias: 'B',
    department_id: 3,
    degree: 'Under Graduation',
  },
  {
    name: 'M.Tech',
    alias: 'M',
    department_id: 3,
    degree: 'Post Graduation',
  },
  {
    name: 'Ph.D',
    alias: 'P',
    department_id: 3,
    degree: 'Doctoral',
  },
  {
    name: 'B.Tech',
    alias: 'B',
    department_id: 4,
    degree: 'Under Graduation',
  },
  {
    name: 'M.Tech',
    alias: 'M',
    department_id: 4,
    degree: 'Post Graduation',
  },
  {
    name: 'Ph.D',
    alias: 'P',
    department_id: 4,
    degree: 'Doctoral',
  },
  {
    name: 'B.Tech',
    alias: 'B',
    department_id: 5,
    degree: 'Under Graduation',
  },
  {
    name: 'M.Tech',
    alias: 'M',
    department_id: 5,
    degree: 'Post Graduation',
  },
  {
    name: 'Ph.D',
    alias: 'P',
    department_id: 5,
    degree: 'Doctoral',
  },
  {
    name: 'B.Tech',
    alias: 'B',
    department_id: 6,
    degree: 'Under Graduation',
  },
  {
    name: 'M.Tech',
    alias: 'M',
    department_id: 6,
    degree: 'Post Graduation',
  },
  {
    name: 'Ph.D',
    alias: 'P',
    department_id: 6,
    degree: 'Doctoral',
  },
  {
    name: 'B.Tech',
    alias: 'B',
    department_id: 7,
    degree: 'Under Graduation',
  },
  {
    name: 'M.Tech',
    alias: 'M',
    department_id: 7,
    degree: 'Post Graduation',
  },
  {
    name: 'Ph.D',
    alias: 'P',
    department_id: 7,
    degree: 'Doctoral',
  },
  {
    name: 'B.Tech',
    alias: 'B',
    department_id: 8,
    degree: 'Under Graduation',
  },
  {
    name: 'M.Tech',
    alias: 'M',
    department_id: 8,
    degree: 'Post Graduation',
  },
  {
    name: 'Ph.D',
    alias: 'P',
    department_id: 8,
    degree: 'Doctoral',
  },
];
