export const nonTeachingStaffData = [
  {
    name: 'John Doe',
    telephone: ['1234567890', '1234567891'],
    email: 'example@gmail.com',
    working_section_id: 1,
    designation: 'Clerk',
    image: '',
    working_department_id: 1,
    role_ids: [1],
  },
  {
    name: 'Jane Doe',
    telephone: ['1234567890', '1234567891'],
    email: 'sample@gmail.com',
    working_section_id: 2,
    designation: 'Clerk',
    image: '',
    working_department_id: 2,
    role_ids: [1, 2],
  },
  {
    name: 'Alice Smith',
    telephone: ['1234567890', '1234567891'],
    email: 'alice.smith@example.com',
    working_section_id: 3,
    designation: 'Manager',
    image: '',
    working_department_id: 3,
    role_ids: [2],
  },
  {
    name: 'Bob Johnson',
    telephone: ['1234567890', '1234567891'],
    email: 'bob.johnson@example.com',
    working_section_id: 4,
    designation: 'Manager',
    image: '',
    working_department_id: 4,
    role_ids: [2, 3],
  },
  {
    name: 'Emma Brown',
    telephone: ['1234567890', '1234567891'],
    email: 'emma.brown@example.com',
    working_section_id: 5,
    designation: 'Assistant',
    image: '',
    working_department_id: 5,
    role_ids: [3],
  },
  {
    name: 'William Davis',
    telephone: ['1234567890', '1234567891'],
    email: 'william.davis@example.com',
    working_section_id: 6,
    designation: 'Assistant',
    image: '',
    working_department_id: 6,
    role_ids: [3, 4],
  },
  {
    name: 'Olivia Wilson',
    telephone: ['1234567890', '1234567891'],
    email: 'olivia.wilson@example.com',
    working_section_id: 7,
    designation: 'Supervisor',
    image: '',
    working_department_id: 7,
    role_ids: [4],
  },
  {
    name: 'James Taylor',
    telephone: ['1234567890', '1234567891'],
    email: 'james.taylor@example.com',
    working_section_id: 8,
    designation: 'Supervisor',
    image: '',
    working_department_id: 8,
    role_ids: [4],
  },
  {
    name: 'Sophia Martinez',
    telephone: ['1234567890', '1234567891'],
    email: 'sophia.martinez@example.com',
    working_section_id: 9,
    designation: 'Clerk',
    image: '',
    working_department_id: 9,
    role_ids: [5],
  },
  {
    name: 'Ethan Anderson',
    telephone: ['1234567890', '1234567891'],
    email: 'ethan.anderson@example.com',
    working_section_id: 10,
    designation: 'Clerk',
    image: '',
    working_department_id: 10,
    role_ids: [5],
  },
];
