export const studentAcademicDetailsData = [
  {
    student_id: 1,
    section: 'A',
    batch: 2023,
    current_semester: 1,
    sgpa: 9.0,
    cgpa: 9.0,
    dmc_urls: ['dmc-url1.com'],
    major_id: 1,
    sub_section: 1,
  },
  {
    student_id: 2,
    section: 'B',
    batch: 2023,
    current_semester: 1,
    sgpa: 9.0,
    cgpa: 9.0,
    dmc_urls: ['dmc-url2.com'],
    major_id: 2,
    sub_section: 2,
  },
  {
    student_id: 3,
    section: 'C',
    batch: 2023,
    current_semester: 1,
    sgpa: 9.0,
    cgpa: 9.0,
    dmc_urls: ['dmc-url3.com'],
    major_id: 3,
    sub_section: 3,
  },
  {
    student_id: 4,
    section: 'D',
    batch: 2023,
    current_semester: 1,
    sgpa: 9.0,
    cgpa: 9.0,
    dmc_urls: ['dmc-url4.com'],
    major_id: 4,
    sub_section: 4,
  },
  {
    student_id: 5,
    section: 'E',
    batch: 2023,
    current_semester: 1,
    sgpa: 9.0,
    cgpa: 9.0,
    dmc_urls: ['dmc-url5.com'],
    major_id: 5,
    sub_section: 5,
  },
  {
    student_id: 6,
    section: 'F',
    batch: 2023,
    current_semester: 1,
    sgpa: 9.0,
    cgpa: 9.0,
    dmc_urls: ['dmc-url6.com'],
    major_id: 6,
    sub_section: 6,
  },
  {
    student_id: 7,
    section: 'G',
    batch: 2023,
    current_semester: 1,
    sgpa: 9.0,
    cgpa: 9.0,
    dmc_urls: ['dmc-url7.com'],
    major_id: 7,
    sub_section: 7,
  },
  {
    student_id: 8,
    section: 'H',
    batch: 2023,
    current_semester: 1,
    sgpa: 9.0,
    cgpa: 9.0,
    dmc_urls: ['dmc-url8.com'],
    major_id: 8,
    sub_section: 8,
  },
  {
    student_id: 9,
    section: 'I',
    batch: 2023,
    current_semester: 1,
    sgpa: 9.0,
    cgpa: 9.0,
    dmc_urls: ['dmc-url9.com'],
    major_id: 9,
    sub_section: 9,
  },
  {
    student_id: 10,
    section: 'J',
    batch: 2023,
    current_semester: 1,
    sgpa: 9.0,
    cgpa: 9.0,
    dmc_urls: ['dmc-url10.com'],
    major_id: 10,
    sub_section: 10,
  },
];
