version: "3.9"
services:
  postgres:
    image: isac:1.0
    build:
      context: ./database
    container_name: 'isac'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ISAC_ADMIN
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=ISAC
  typesense:
    image: typesense/typesense:0.25.2
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
