// Director Message translations

export interface DirectorMessageTranslations {
  title: string;
  message: string[];
}

export const directorMessageEn: DirectorMessageTranslations = {
  title: `Director's Message`,
  message: [
    `India, the land of seekers, is at the cusp of becoming Vishwa Guru all over again after 1100 years of subjugation, wars, annexures and humiliation. It is again a free country due to the sacrifices made by our leaders, freedom fighters and has learnt the art of standing tall in the midst of many a challenge of building the nation with its rich diversity, cultures, languages all over again since the last 75 years. Unity in Diversity is our mantra while making our nation stronger in every sphere.`,
    `The land of Kurukshetra also referred to as Dharma Kshetra has taught us to be righteous in our demeanour, uphold values, make one self-strong to desist any attacks on self or subjects who are vulnerable. The celestial song of Bhagavat Gita teaches us to achieve a 3600   development of Holistic personality and seeks to dispel all our doubts, predicaments, and guides us to search and explore self and the material world outside.`,
    `It was proved without doubt over centuries that no nation has ever risen to the stature of a world leader or a happy nation without educating its subjects. The role of Universities and Centres of Excellence was never in question. Creativity, innovation and hands on experience were given importance and nature was the experimental laboratory to unravel the secrets of the universe. The Universities in the form of Nalanda and Takshashila rose to stature of international level learning centres of nurturing young minds to explore themselves and unravel the secrets of nature in a variety of trades known as 64 art forms. They explored skills through recitation, hands on experience and experiential learning. The famous Guru Shishya Parampara was passed on through ages and generations.`,
    `Takshashila University was famous not because of it’s never ending collection of scripts.  It was famous because of knowledge that it had to offer.  Knowledge on how best a human being can function in this world.  Knowledge of using the intelligence that our race possesses.`,
    `What could be the right setting for a great nation like India and NIT Kurukshetra to tap the potentialities of young minds who are drawn from across the nation through a rigorous process of selection through national level testing. These young boys and girls toil really hard to reach these portals of learning. It is our endeavour to provide the right environment of teaching, learning and allow them to explore their self and progress not only advancing technologies but also promoting their innate skills of creativity and innovative traits to be  the guiding forces in solving many a societal problems and set an example that universities and centre of excellence are not isolated spaces for exploration of knowledge alone but contribute to the growth of the nation, through setting up of incubation centres, promote start up culture and entrepreneurial mindset. In this direction, NIT KKR would end the motions of rote learning and changing the setting for critical thinking, enquiry, debate and discussions while promoting experiential learning by connecting these young minds through NIT KKR – Local community link. No education is complete if the scholar is unable to move from levels of learning to achieve knowledge leading to wisdom.`,
    `Last two years, during the pandemic times, the whole world lost many a life, lost livelihood, nations suffered due to lack of growth and the challenges of such testing times led many to depression, anxiety, suicidal tendencies, loss of beloved etc., We are still grappling to come to terms with the pandemic and have taken the lead to bring a semblance of order albeit on virtual platforms. Some hard lessons have been learnt and education sector is one among the most affected area, where young minds were locked physically, mentally, emotionally and spiritually. The time is ripe to explore these innate qualities in achieving human excellence.`,
    `Having taken over the charge of Director of one of the oldest REC, now transformed as NIT with the status of Institution of National Importance on 05th February, 2022 (Basant Panchami), I along with my teaching, non-teaching faculty and support staff welcome you and are eagerly waiting for all our dear students to come to the campus, leaving no stone unturned in preparing ourselves to welcome you, albeit after two long years of isolation through online teaching learning etc. As the leader I assure you that you will be pampered by creating an atmosphere of comfort of a home, spaces much bigger than a home to explore oneself, provide facilities to explore oneself and material progress, allowing you to dream big. I personally wish each one of you become passionate about life and serve the society at large in the form of technocrats, business men, world leaders etc.  I assure that implementation of National Education Policy 2020 (NEP 2020) shall be top most priority.`,
    `The logo of NIT KKR, has a Motto which reads as follows`,
    `"Shramaye Anavarat chesta cha"`,
    `which means hard work and consistent efforts leads to excellence.`,
    `I congratulate all student aspirants to have made it to enter portals of NIT KKR and Wish all family members of NIT Kurukshetra all success in all their endeavours.`,
    `JAI HIND……….`,
    `Prof. B. V. Ramana Reddy`,
  ],
};

export const directorMessageHi: DirectorMessageTranslations = {
  title: 'निदेशक महोदय का संदेश',
  message: [
    `साधकों की भूमि भारत, 1100 वर्षो की अधीनता, युद्ध, अनुबंध और अपमान के बाद फिर से विश्व गुरु बनने के कगार पर है । हमारे नेताओं, स्वतंत्रता सेनानियों के बलिदान के कारण यह फिर से एक स्वतंत्र देश है और इसने पिछले 75 वर्षो से अपनी समृद्ध विविधता, संस्कृतियों , भाषाओं के साथ राष्ट्र के निर्माण की चुनौतियों के बीच लंबे समय से खड़े होने की कला सीखी है । हमारे राष्ट्र को हर क्षेत्र में मजबूत बनाते हुए विविधता में एकता हमारा मंत्र है ।`,
    `कुरुक्षेत्र की भूमि को धर्म क्षेत्र के रूप में भी जाना जाता है, जिसने हमें अपने आचरण में धर्मी होना, मूल्यों को बनाए रखना, स्वयं को या कमजोर विषयों पर किसी भी हमले को रोकने के लिए आत्म – मजबूत बनाना सिखाया है । भगवद्‌ गीता का दिव्य संदेश हमें समग्र व्यक्तित्व का 360 डिग्री विकास प्राप्त करना सिखाता है और हमारे सभी संदेहों, दुर्दशाओं को दूर करने का प्रयास करता है और हमें खोजने, स्वयं और भौतिक दुनिया को तलाशने के लिए मार्गदर्शन करता है ।`,
    `सदियों से बिना किसी संदेह के यह साबित हो गया है कि कोई भी राष्ट्र अपनी प्रजा को शिक्षित किए बिना कभी भी विश्व नेता या खुशहाल राष्ट्‌ के कद तक नहीं बढ़ा है। विश्वविद्यालयों और उत्कृष्टता केंद्रों की भूमिका कभी सवालों के घेरे में नहीं थी। रचनात्मकता, नवीनता और व्यावहारिक अनुभव को महत्व दिया गया और प्रकृति ब्रह्मांड के रहस्यों को जानने की प्रायोगिक प्रयोगशाला थी। नालंदा और तक्षशिला के रूप में विश्वविद्यालय अंतर्राष्ट्रीय स्तर के शिक्षा केंद्रों के कद तक बढ़ गए, जो कि 64 कला रूपों के रूप में जाने जाने वाले विभिन्‍न प्रकार की गतिविधियों में खुद को तलाशने और प्रकृति के रहस्यों को उजागर करने के लिए युवा दिमाग का पोषण करते रहे | उन्होंने सस्वर पाठ, अनुभव और अनुभवात्मक शिक्षा के माध्यम से कौशल का पता लगाया । प्रसिद्ध गुरु शिष्य परम्परा युगों और पीढ़ियों से चली आ रही थी ।`,
    `तक्षशिला विश्वविद्यालय कभी न खत्म होने वाले लिपियों के संग्रह के कारण ही प्रसिद्ध नहीं था बल्कि यह मौजूद ज्ञान के कारण प्रसिद्ध था कि इंसान कैसे सबसे अच्छा काम कर सकता है । हमारी जाति के पास बुद्धि का उपयोग करने का ज्ञान है।`,
    `भारत और एनआईटी क्रुक्षेत्र जैसे महान राष्ट्‌ के लिए राष्ट्रीय स्तर के परीक्षण के माध्यम से चयन की कठोर प्रक्रिया के माध्यम से देश भर से चयनित हुए युवा दिमाग की क्षमता का दोहन करने के लिए सही विधि क्‍या हो सकती है । ये युवा लड़के और लड़कियां सीखने के इन मचों तक पहुंचने के लिए वास्तव में कठिन परिश्रम करते हैं । यह हमारा प्रयास है कि हम शिक्षण, सीखने का सही वातावरण प्रदान करें और उन्हें न केवल आगे बढ़ने वाली प्रौद्योगिकियों को स्वयं और प्रगति का पता लगाने की अनुमति दें बल्कि कई सामाजिक समस्याओं को हल करने और सेट करने में मार्गदर्शक शक्ति बनने के लिए रचनात्मकता और नवीन लक्षणों के अपने जन्मजात कौशल को बढ़ावा दें । एक ऐसा उदाहरण प्रस्तुत कर दें कि विश्वविद्यालय और उत्कृष्टता केंद्र अकेले ज्ञान की स्थापना के लिए अलग स्थान न बन जाए बल्कि स्टार्ट-अप संस्कृति और उद्यमशीलता की मानसिकता को बढ़ावा देकर राष्ट्‌ के विकास में योगदान कर सकें। इस दिशा में , एनआईटी कुरुक्षेत्र इन युवा दिमागों को एनआईटी कुरुक्षेत्र – स्थानीय समुदाय लिंक के माध्यम से जोड़कर अनुभवात्मक सीखने को बढ़ावा देते हुए महत्वपूर्ण सोच, पूछताछ, बहस और चर्चा के लिए सेटिंग बदलने और रटने की गति को समाप्त करेगा। कोई भी शिक्षा पूर्ण नहीं है, यदि विद्वान ज्ञान की ओर ले जाने वाले तथा ज्ञान को प्राप्त करने के लिए सीखने के स्तर से आगे बढ़ने में असमर्थ है ।`,
    `पिछले दो वर्षों में, महामारी के समय में , पूरी दुनिया में कई लोगों की जान गंवाई, आजीविका खो दी, राष्ट्रों को विकास की कमी का सामना करना पड़ा और इस तरह के परीक्षण के समय की चुनौतियों ने कई लोगों को अवसाद, चिंता, आत्महत्या की प्रवृत्ति, प्रिय की हानि आदि का कारण बना दिया । हम अभी भी महामारी से निपटने के लिए जूझ रहे हैं और वर्चुअल प्लेटफॉर्म पर ऑर्डर की समानता लाने का बीड़ा उठाया है । कुछ कठिन सबक सीखे गए हैं और शिक्षा क्षेत्र सबसे अधिक प्रभावित क्षेत्रों में से एक है, जहां युवा दिमाग शारीरिक,मानसिक, भावनात्मक और आध्यात्मिक रूप से अस्थिर थे । मानवीय उत्कृष्टता प्राप्त करने में इन सहज गुणों का पता लगाने का समय आ गया है ।`,
    `पुराने १६९ में से एक के निदेशक का पदभार ग्रहण करने के बाद, अब 05 फरवरी, 2022 (बसंत पंचमी) को राष्ट्रीय महत्व के संस्थान की स्थिति के साथ एनआईटी के रूप में परिवर्तित हुआ, मैं अपने शिक्षण, गैर-शिक्षण संकाय और सहायक कर्मचारियों के साथ आपका स्वागत करता हूं और हम ऑनलाइन शिक्षण, सीखने आदि के माध्यम से दो साल के अलगाबव के बाद प्रिय छात्रों के परिसर में आने के लिए बेसब्री से इंतजार करते हुए, स्वागत करने के लिए पूरी तरह से तैयार है। नेता के रूप में मैं आपको विश्वास दिलाता हूं कि घर के अनुरूप माहौल बनाकर, अपने आप को तलाशने के लिए घर से अधिक जगह बनाकर, खुद को तलाशने के लिए सुविधाएं और भौतिक प्रगति प्रदान करके, आपको बड़े सपने देखने की अनुमति देकर लाड्-प्यार करूंगा । मैं व्यक्तिगत रूप से कामना करता हूं कि आप में से प्रत्येक जीवन के प्रति जुनूनी बनें और टेक्नोक्रेट, व्यवसायी , विश्व नेताओं आदि के रूप में बड़े पैमाने पर समाज की सेवा करें। मैं विश्वास दिलाता हूं कि राष्ट्रीय शिक्षा नीति 2020 (एनईपी 2020) का कार्यान्वयन सर्वोच्च प्राथमिकता होगी ।`,
    `एनआईटी क्रुक्षेत्र के लोगो में एक आदर्श वाक्य है जो इस प्रकार है`,
    `"श्रमोऽनवरत चेष्टा च"`,
    `जिसका अर्थ है कड़ी मेहनत और लगातार प्रयास उत्कृष्टता की ओर ले जाते हैं ।`,
    `मैं सभी छात्र उम्मीदवारों को एनआईटी क्रुक्षेत्र के प्रांगण में प्रवेश करने के लिए बधाई देता हूं और एनआईटी क््‌रुक्षेत्र के सभी परिवार के सदस्यों को उनके सभी प्रयासों में सफलता की कामना करता हूं । मैं लगभग दो साल के लॉकडाउन जैसी स्थिति के बाद आपका स्वागत करने का बेसब्री से इंतजार कर रहा हूं, जिसमें तीन सौ एकड़ के विशाल परिसर में एक साथ आनंद और मस्ती का आनंद लिया जा रहा है। मैं अपने प्यारे छात्रों के सभी माता-पिता को विश्वास दिलाता हूं कि आपके बच्चे सुरक्षित हाथों में हैं, उनके साथ यथासंभव प्यार और उनकी देखभाल की जाएगी ।`,
    `जय हिन्द…………`,
    `प्रो. बी. वी. रमना रेड्डी`,
  ],
};
