name: Sync Google Drive to S3

on:
  push:
    branches: drive-to-s3
  workflow_dispatch: #can be triggered manually
  schedule:
    - cron: "0 0 * * *" # every day at 00:00 utc

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Install AWS CLI and GDrive
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -Ls https://github.com/prasmussen/gdrive/releases/download/2.1.0/gdrive-linux-x64 > gdrive
          chmod +x gdrive
          sudo mv gdrive /usr/local/bin/
          aws --version
          gdrive version

      - name: Authenticate GDrive
        env:
          GDRIVE_TOKEN: ${{ secrets.GDRIVE_TOKEN }}
        run: |
          echo "${GDRIVE_TOKEN}" > ~/.gdrive_token
          gdrive about

      - name: Download Folder from Google Drive
        run: |
          mkdir -p downloads
          gdrive download --recursive --path downloads/ <YOUR_GOOGLE_DRIVE_FOLDER_ID>

      - name: Unzip Downloaded Folder
        run: |
          for zip_file in downloads/*.zip; do
            unzip -o "$zip_file" -d downloads/unzipped/
          done

      - name: Rename Existing Folder in S3 to Backup
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
        run: |
          aws s3 mv s3://your-bucket-name/isaac-s3-images/ s3://your-bucket-name/backup/ --recursive

      - name: Upload Folder to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
        run: |
          aws s3 cp downloads/unzipped/ s3://your-bucket-name/isaac-s3-images/ --recursive --acl public-read

      - name: Delete Backup Folder from S3
        if: success()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 rm s3://your-bucket-name/backup/ --recursive